//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaProject.ADOApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ID { get; set; }
        public Nullable<int> id_rental { get; set; }
        public Nullable<int> id_film { get; set; }
    
        public virtual Film Film { get; set; }
        public virtual Rental Rental { get; set; }
    }
}
